Add functions to calculate cycle closure
OpenFreeEnergy/cinnabar pull request #107
Opened 2023-11-06 12:17 UTC by hannahbaumann

## Description
Provide a brief description of the PR's purpose here.

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - [ ] TODO 1

## Questions
- [ ] Question1

## Status
- [ ] Ready to go

2023-11-06 12:17 UTC, pep8speaks commented
Hello @hannahbaumann! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`cinnabar/femap.py`](https://github.com/OpenFreeEnergy/cinnabar/blob/2276ea7c7dd04b0e5f0fa9491f23c898bd6295a0/cinnabar/femap.py):

> [Line 262:5](https://github.com/OpenFreeEnergy/cinnabar/blob/2276ea7c7dd04b0e5f0fa9491f23c898bd6295a0/cinnabar/femap.py#L262): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 327:47](https://github.com/OpenFreeEnergy/cinnabar/blob/2276ea7c7dd04b0e5f0fa9491f23c898bd6295a0/cinnabar/femap.py#L327): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2026-05-19 13:18 UTC, jthorton commented on cinnabar/femap.py
> +            # to get cycle closure error PER EDGE
If this were per edge I would expect it to be over `len(cycle)`lets update the comment to something like normalise by sqrt(cycle length) to allow comparison across different length cycles?

2026-05-19 13:21 UTC, jthorton commented on cinnabar/femap.py
> +            # to get cycle closure error PER EDGE
Could we also report the uncertainty-normalised closure as `abs(sum_ddgs) / sqrt(sum sigma_i^2)` where sigma_i is the uncertainty of the ith edge in the cycle, it might be useful to keep the uncertainty in mind when looking at these errors or is there any other standard way of doing this, something like a z-score for the error?

2026-05-19 14:03 UTC, hannahbaumann commented
<img width="1464" height="1162" alt="cycle_closure" src="https://github.com/user-attachments/assets/093d6090-5865-4ef3-ab7b-4a2759c71df3" />

2026-05-20 08:00 UTC, hannahbaumann commented
pre-commit.ci autofix

2026-05-20 08:01 UTC, hannahbaumann commented on cinnabar/femap.py
> +            # to get cycle closure error PER EDGE
I added this!

2026-05-27 09:58 UTC, jthorton commented on cinnabar/femap.py
> +    def get_cycle_closure(self, max_cycle_length: int = 5) -> list[tuple[str, float]]:
How do you feel about calling this something like `get_cycle_closure_dataframe` so it aligns with the other methods on FEMap?

2026-05-27 09:59 UTC, jthorton commented on cinnabar/femap.py
> +        edge_uncertainty = {(a, b): d["calc_dDDG"] for a, b, d in network.edges(data=True)}
Can we use `get_relative_dataframe` as it handles multiple sources correctly and we want to drop `to_legacy_graph`.

2026-05-27 10:00 UTC, jthorton commented on cinnabar/femap.py
> +                    break
We also need to do this per source in the FEMap.

2026-05-27 10:01 UTC, jthorton commented on cinnabar/femap.py
> +            cycle closure error descending.
Let's list the column names exactly as they appear, similar to the `get_relative_dataframe` function.

2026-05-27 10:08 UTC, jthorton commented on cinnabar/femap.py
> +    def get_cc_based_edge_statistics(self, max_cycle_length: int = 5) -> pd.DataFrame:
Can we work this into the theme and get dataframe in the name so people know what to expect not sure how to shorten and add that though.

2026-05-27 10:10 UTC, jthorton commented on cinnabar/femap.py
> +        likely candidates for re-simulation.
Make it clear that these are the simulated edges we are looking at, maybe we can add some interpretation of the results to the docs rather than the method? 
```suggestion
        For each simulated edge, report how many cycles it appears in and
        the mean and max cycle closure error of those cycles per source.
```

2026-05-27 10:11 UTC, jthorton commented on cinnabar/femap.py
> +                    "max_cc (kcal/mol)": round(max(ccs), 3),
Add source to the output and sort by `["source", "mean_cc (kcal/mol)"]`

2026-05-27 10:13 UTC, jthorton commented on cinnabar/plotting.py
> +    ax.hist(errors, bins="auto", alpha=0.6, color="steelblue")
Let the user pass in the bin width or the bins array? Or we should standardise on a width value.

2026-05-27 10:14 UTC, jthorton commented on cinnabar/plotting.py
> +    df = fe_map.get_cycle_closure(max_cycle_length=max_cycle_length)
We need to plot a histogram per source or let the user define a list of sources to plot.

2026-05-29 13:24 UTC, IAlibay commented on cinnabar/femap.py
> +    def get_cycle_closure(self, max_cycle_length: int = 5) -> list[tuple[str, float]]:
```suggestion
    def get_cycle_closure(self, max_cycle_length: int = 5) -> pd.DataFrame:
```

2026-05-29 13:24 UTC, IAlibay commented on cinnabar/femap.py
> +                        "cc_unc_normalized (kcal/mol)": round(cc_uncertainty_normalized, 2),
Please correct me, but don't the units cancel out for this one?

2026-05-29 13:24 UTC, IAlibay commented on cinnabar/femap.py
> +                # Normalize by sqrt(cycle length) to allow comparison across
Probably want to mention this in the docstring.

2026-05-29 13:24 UTC, IAlibay commented on cinnabar/femap.py
> +                # Normalize by sqrt(cycle length) to allow comparison across
It may be useful to have the unnormalized variant on hand too?

2026-05-29 13:24 UTC, IAlibay commented on cinnabar/femap.py
> +                # Normalize by sqrt(cycle length) to allow comparison across
Do we have some previously published information of someone using this? This roughly makes sense, but it's not immediately clear to me that it's standard practice.

2026-05-29 14:19 UTC, hannahbaumann commented on cinnabar/femap.py
> +    def get_cycle_closure(self, max_cycle_length: int = 5) -> list[tuple[str, float]]:
Changed this!

2026-05-29 14:20 UTC, hannahbaumann commented on cinnabar/femap.py
> +        edge_uncertainty = {(a, b): d["calc_dDDG"] for a, b, d in network.edges(data=True)}
Changed this!

2026-05-29 14:20 UTC, hannahbaumann commented on cinnabar/femap.py
> +                    break
Changed this!

2026-05-29 14:20 UTC, hannahbaumann commented on cinnabar/femap.py
> +            cycle closure error descending.
Updated this!

2026-05-29 14:20 UTC, hannahbaumann commented on cinnabar/femap.py
> +    def get_cc_based_edge_statistics(self, max_cycle_length: int = 5) -> pd.DataFrame:
Changed this to `get_cycle_closure_edge_statistics_dataframe`

2026-05-29 14:21 UTC, hannahbaumann commented on cinnabar/femap.py
> +                    "max_cc (kcal/mol)": round(max(ccs), 3),
Changed this!

2026-05-29 14:24 UTC, hannahbaumann commented on cinnabar/plotting.py
> +    ax.hist(errors, bins="auto", alpha=0.6, color="steelblue")
Changed this, added a default parameter of 0.5 to the arguments.

2026-05-29 14:24 UTC, hannahbaumann commented on cinnabar/plotting.py
> +    df = fe_map.get_cycle_closure(max_cycle_length=max_cycle_length)
Changed this. For now it's putting all histograms into a single plot, because I thought that maybe people don't have lots of sources, or should we do a separate plot per source?

2026-05-29 14:26 UTC, hannahbaumann commented
pre-commit.ci autofix

2026-05-29 14:43 UTC, hannahbaumann commented
pre-commit.ci autofix

2026-05-29 14:46 UTC, hannahbaumann commented on cinnabar/plotting.py
> +) -> plt.Figure:
```suggestion
) -> plt.Figure | None:
```

2026-06-01 08:57 UTC, hannahbaumann commented on cinnabar/femap.py
> +                # Normalize by sqrt(cycle length) to allow comparison across
That would be me in the SepTop paper =)
I think the idea (coming from Eric D.) was that the expected accumulated error scales at sqrt(n) if the errors are considered independent, giving an approximate contribution of a single edge to the cycle closure error.

2026-06-01 09:10 UTC, hannahbaumann commented on cinnabar/femap.py
> +                # Normalize by sqrt(cycle length) to allow comparison across
Added this!

2026-06-01 09:10 UTC, hannahbaumann commented on cinnabar/femap.py
> +                # Normalize by sqrt(cycle length) to allow comparison across
Added an explanation for the different cases to the doc string.

2026-06-01 09:12 UTC, hannahbaumann commented
pre-commit.ci autofix

2026-06-01 10:03 UTC, jthorton commented on cinnabar/femap.py
> +        max_cycle_length : int, optional
```suggestion
        max_cycle_length : int, default 5
```

2026-06-01 10:05 UTC, jthorton commented on cinnabar/femap.py
> +        max_cycle_length : int, optional
```suggestion
        max_cycle_length : int, default 5
```

2026-06-01 10:09 UTC, jthorton commented on cinnabar/plotting.py
> +    bin_width : float, optional
```suggestion
    filename : str, default None
        If provided, the plot will be saved to this filename.
    max_cycle_length : int, default 5
        Only consider cycles up to this length. Defaults to 5.
        The matplotlib Figure object, which can be edited further.
    sources : list[str], default None
        List of sources to plot. If None, all sources are plotted.
    bin_width : float, default 0.5
```

2026-06-01 10:12 UTC, jthorton commented on cinnabar/plotting.py
> +            return None
the other types of plots all use `ValueError` when this type of validation fails, lets make it consistent and do the same here!

2026-06-01 10:13 UTC, jthorton commented on cinnabar/femap.py
> +          calculated as ``abs(sum_ddgs) / sqrt(sum_var)``.
Do you want to add the septop paper as a reference in the doc string for the `cc_per_edge`?

2026-06-01 10:14 UTC, jthorton commented on cinnabar/tests/test_plotting.py
> +def test_plot_cycle_closure(fe_map, tmp_path):
Can we add a test for more than once source in the dataframes.

2026-06-01 10:14 UTC, jthorton commented on cinnabar/tests/test_femap.py
> +def test_get_cycle_closure_perfect_cycle(perfect_cycle):
Can we add a test for more than one source in the dataframe as well.

2026-06-01 10:15 UTC, jthorton requested changes
Thanks @hannahbaumann, just a couple of minor things to add, and please add a news entry!

2026-06-01 11:08 UTC, hannahbaumann commented on cinnabar/plotting.py
> +            return None
Changed this here and also above to raise a ValueError instead.

2026-06-01 11:08 UTC, hannahbaumann commented on cinnabar/femap.py
> +          calculated as ``abs(sum_ddgs) / sqrt(sum_var)``.
added this!

2026-06-01 11:08 UTC, hannahbaumann commented on cinnabar/tests/test_plotting.py
> +def test_plot_cycle_closure(fe_map, tmp_path):
Added this!

2026-06-01 11:08 UTC, hannahbaumann commented on cinnabar/tests/test_femap.py
> +def test_get_cycle_closure_perfect_cycle(perfect_cycle):
Added this!

2026-06-01 11:09 UTC, IAlibay requested changes
Couple of things

2026-06-01 11:09 UTC, IAlibay commented on cinnabar/femap.py
> +                    cc_z_score = abs(sum_ddgs) / math.sqrt(sum_var)
If the uncertainty is 0 (e.g. if someone failed to feed it in), I believe this will cause a ZeroDivisionError.

2026-06-01 11:09 UTC, IAlibay commented on cinnabar/femap.py
> +                cc = row["cc_per_edge (kcal/mol)"]
Both the column names and docstring don't make it clear that you're using `cc_per_edge` (i.e. the cycle closure divided by sqrt(cycle_length).

It would be good to make that clearer.

2026-06-01 11:09 UTC, IAlibay commented on cinnabar/femap.py
> +        comp_df = self.get_relative_dataframe()
You call `get_relative_dataframe` here but it's also called when you call `get_cyccle_closure_dataframe` is there any way to just directly use `cc_df`?

2026-06-01 11:09 UTC, IAlibay commented on cinnabar/plotting.py
> +    filename: Optional[str] = None,
Can you switch to str | None and avoid importing Optional & Union?

2026-06-01 11:09 UTC, IAlibay commented on cinnabar/plotting.py
> +        The matplotlib Figure object, which can be edited further.
This seems like a typo?

2026-06-01 11:09 UTC, IAlibay commented on cinnabar/plotting.py
> +) -> plt.Figure | None:
Add a return entry to the docstring?

2026-06-01 11:09 UTC, hannahbaumann commented on cinnabar/femap.py
> +                    cc_z_score = abs(sum_ddgs) / math.sqrt(sum_var)
Added a check for this!

2026-06-01 11:50 UTC, hannahbaumann commented on cinnabar/femap.py
> +        comp_df = self.get_relative_dataframe()
You're right, i think getting the edges directly from cc_df should also work, I updated this, unless I'm missing something? I also added a test that has multiple cycles to check for this.

2026-06-01 12:22 UTC, hannahbaumann commented
pre-commit.ci autofix

2026-06-01 13:03 UTC, hannahbaumann commented on cinnabar/plotting.py
> +        The matplotlib Figure object, which can be edited further.
Ah, this must have come from not properly resolving a merge conflict, this was part of the return from the other function.. removed this here and added a proper returns below.

2026-06-01 13:03 UTC, hannahbaumann commented on cinnabar/plotting.py
> +) -> plt.Figure | None:
Done!

2026-06-01 13:05 UTC, hannahbaumann commented on cinnabar/femap.py
> +                cc = row["cc_per_edge (kcal/mol)"]
Changed this!

2026-06-01 13:05 UTC, hannahbaumann commented on cinnabar/plotting.py
> +    filename: Optional[str] = None,
Done!

2026-06-02 11:36 UTC, IAlibay reviewed
Couple of small things - mainly a question on simple_cyles and maybe if cycle_basis should be used instead?

2026-06-02 11:36 UTC, IAlibay commented on cinnabar/femap.py
> +        - cc_unc_normalized
Is this missing `cc_per_edge`?

2026-06-02 11:36 UTC, IAlibay commented on cinnabar/plotting.py
> +import warnings
Is this unused?

2026-06-02 11:36 UTC, IAlibay commented on cinnabar/tests/test_plotting.py
> +import networkx as nx
Is this unused?

2026-06-02 11:36 UTC, IAlibay commented on cinnabar/femap.py
> +            cycles = [c for c in nx.simple_cycles(network.to_undirected()) if len(c) <= max_cycle_length]
I've been staring at this for a while and it's not immediately clear to me if calling `simple_cycles` on an undirected graph won't yield the same cycle in both orientation - i.e. [A, B, C] and [A, C, B].

Would this be intended behaviour? If not, should `cycle_basis` be used instead?

2026-06-02 14:42 UTC, jthorton commented on cinnabar/femap.py
> +        - cc_unc_normalized
```suggestion
        - cc_per_edge (kcal/mol)
        - cc_unc_normalized
```

2026-06-02 14:44 UTC, jthorton commented on cinnabar/femap.py
> +            cycles = [c for c in nx.simple_cycles(network.to_undirected()) if len(c) <= max_cycle_length]
Wouldn't this show up in `test_get_cycle_closure_perfect_cycle`, there we check that the resulting dataframe has length 1 so only a single cycle is found.

2026-06-02 15:10 UTC, hannahbaumann commented on cinnabar/femap.py
> +            cycles = [c for c in nx.simple_cycles(network.to_undirected()) if len(c) <= max_cycle_length]
It looks like `simple_cycles` filters those out:

> A “simple cycle”, or “elementary circuit”, is a closed path where no node appears twice. In a directed graph, two simple cycles are distinct if they are not cyclic permutations of each other. In an undirected graph, two simple cycles are distinct if they are not cyclic permutations of each other nor of the other’s reversal.
https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.cycles.simple_cycles.html

But I could also switch to `cycle_basis` if that would be better overall!

2026-06-02 15:16 UTC, hannahbaumann commented on cinnabar/tests/test_plotting.py
> +import networkx as nx
Removed!

2026-06-02 15:16 UTC, hannahbaumann commented on cinnabar/plotting.py
> +import warnings
Removed!

2026-06-02 15:16 UTC, hannahbaumann commented on cinnabar/femap.py
> +        - cc_unc_normalized
Added this!

2026-06-02 15:39 UTC, jthorton commented on cinnabar/femap.py
> +            cycles = [c for c in nx.simple_cycles(network.to_undirected()) if len(c) <= max_cycle_length]
Thinking about this more, maybe `cycle_basis` would be better. Take the following example from the networkx docs:

```python
G = nx.Graph()
nx.add_cycle(G, [0, 1, 2, 3])
nx.add_cycle(G, [0, 3, 4, 5])
list(nx.simple_cycles(G))
> [[0, 1, 2, 3], [0, 1, 2, 3, 4, 5], [0, 3, 4, 5]]
```
Would we want the values on the smallest possible cycles of the graph? The super cycles formed by combinations of cycles don't tell us anything new do they?

2026-06-03 07:09 UTC, hannahbaumann commented on cinnabar/femap.py
> +            cycles = [c for c in nx.simple_cycles(network.to_undirected()) if len(c) <= max_cycle_length]
I think my thought process from back when I was doing that as a grad student was that if we included more cycles (so also the super cycles) the risk of "missing" bad edges would be lower where by missing I mean that some cycles can give a low cycle closure by chance (bad edges but cancelation of errors). And then I included the `max_cycle_length` since the super large cycles don't seem very meaningful. In addition I had used this to then count how often an edge appears in a bad cycle, and there the super cycles are helpful to pin down the bad egg(s) in the cycle.
But maybe you're right and including those super cycles wouldn't really add that information?

2026-06-03 11:53 UTC, jthorton commented on cinnabar/femap.py
> +            cycles = [c for c in nx.simple_cycles(network.to_undirected()) if len(c) <= max_cycle_length]
Okay that makes sense and seems to agree with the observations in https://pubs.acs.org/doi/10.1021/acs.jcim.5c00554 where closing the basis cycles does not mean the larger cycles will close, lets go with simple_cycles and come back to this if we find any issues!

2026-06-03 12:00 UTC, jthorton approved these changes
Thanks @hannahbaumann LGTM!

2026-06-03 12:30 UTC, IAlibay commented on cinnabar/femap.py
> +            cycles = [c for c in nx.simple_cycles(network.to_undirected()) if len(c) <= max_cycle_length]
It would be good to record this somewhere in an issue - otherwise we might never come back to it / remember why we made this decision.

2026-06-03 12:33 UTC, IAlibay approved these changes
I'll approve but I would like it if we could document some of the decision making on how we gather cycles.

2026-06-03 12:33 UTC, IAlibay commented on cinnabar/femap.py
> +            cycles = [c for c in nx.simple_cycles(network.to_undirected()) if len(c) <= max_cycle_length]
Probably should document this cycle choosing behaviour too somewhere user facing (it'd be ok as a separate issue / PR).

2026-06-03 13:10 UTC, jthorton commented on cinnabar/femap.py
> +            cycles = [c for c in nx.simple_cycles(network.to_undirected()) if len(c) <= max_cycle_length]
Wait do we want this to be `undirected`, this will miss self-loops if users run forward and backward edges which might be nice to include in the output?

2026-06-03 14:02 UTC, hannahbaumann commented on cinnabar/femap.py
> +            cycles = [c for c in nx.simple_cycles(network.to_undirected()) if len(c) <= max_cycle_length]
Opened an issue here: https://github.com/OpenFreeEnergy/cinnabar/issues/218

2026-06-03 14:36 UTC, hannahbaumann commented on cinnabar/femap.py
> +            cycles = [c for c in nx.simple_cycles(network.to_undirected()) if len(c) <= max_cycle_length]
As discussed offline, the directed graph would not catch something like this as a cycle: A->B; C->B; C->A.
For now we will leave it as is, but opening an issue that this should be fixed in the future (https://github.com/OpenFreeEnergy/cinnabar/issues/219)

2026-06-03 14:36 UTC, jthorton commented on cinnabar/femap.py
> +            cycles = [c for c in nx.simple_cycles(network.to_undirected()) if len(c) <= max_cycle_length]
Spoke on slack about this, this does not pick up cycles in the directed case for cycles like `A->B; C->B; C->A?` we will update the notes of the function to say this does not cover self loops.

2026-06-03 14:37 UTC, hannahbaumann commented on cinnabar/femap.py
> +          calculated as ``abs(sum_ddgs) / sqrt(sum_var)``.
```suggestion
          calculated as ``abs(sum_ddgs) / sqrt(sum_var)``.
          
      The function currently does not consider self loop edges, e.g. A-->B and B-->A edges. 
```

2026-06-03 14:38 UTC, hannahbaumann commented on cinnabar/femap.py
> +            cycles = [c for c in nx.simple_cycles(network.to_undirected()) if len(c) <= max_cycle_length]
```suggestion
            # Using the undirected graph means that self loop edges are not considered. 
            cycles = [c for c in nx.simple_cycles(network.to_undirected()) if len(c) <= max_cycle_length]
```

2026-06-03 14:39 UTC, hannahbaumann commented on cinnabar/femap.py
> +      The function currently does not consider self loop edges, e.g. A-->B and B-->A edges.
```suggestion
        - ``cc_unc_normalized``: the cycle closure error divided by its propagated uncertainty,
          calculated as ``abs(sum_ddgs) / sqrt(sum_var)``.
          
        The function currently does not consider self loop edges, e.g. A-->B and B-->A edges. 
```

2026-06-03 14:40 UTC, hannahbaumann commented
pre-commit.ci autofix

2026-06-03 14:44 UTC, merged